namespace: dev
KC_HOSTNAME: logcorner.datasynchro.com

KC_IMAGE: "quay.io/keycloak/keycloak:26.0.5"
replicaCount: 1

configMap:
  name: keycloak-config
  KC_DB_URL: "jdbc:postgresql://datasynchrodevpg-srv.postgres.database.azure.com/datasynchro"
  KC_DB_USERNAME: "datasynchro"

secret:
  name: keycloak-secret
  KC_DB_PASSWORD: "{{set inline }}"