apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-configmap
  namespace: {{ .Values.namespace }}
  labels:
    app: "keycloak-deployment"
data:
  KC_DB_URL: "jdbc:postgresql://datasynchrodevpg-srv.postgres.database.azure.com/datasynchro"
  KC_DB_USERNAME: "datasynchro"
