apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: "keycloak-deployment"
stringData:
  KC_DB_PASSWORD: {{ .Values.secret.KC_DB_PASSWORD }}
