apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - name: curl
    image: curlimages/curl:latest
    command: ["/bin/sh", "-c", "sleep 3600"]
    # Using sleep to keep the pod alive for testing
  restartPolicy: Always
